### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by ShangwenWang** [bears-bugs/bears-benchmark#327]
Dear authors,
Thanks for providing such a benchmark. I find it is really helpful.
My question is about how to run the program against the test cases since I note each program version is equipped with corresponding test suite.
Through the README file, I think I can run _checkout_ and _compile_ files. Am I right?

**Comment by fermadeiral** [comment]
Hi @ShangwenWang,

> Thanks for providing such a benchmark. I find it is really helpful.

I'm glad to hear that!

> [...] I can run checkout and compile files. Am I right?

Yes. The script to compile also runs `mvn test` on the buggy program versions.

**Comment by ShangwenWang** [comment]
@fermadeiral 
Thanks. Then I'd like to know the differences between suffix _all_ and _bug_.

**Comment by fermadeiral** [comment]
> Then I'd like to know the differences between suffix all and bug.

The scripts with suffix *all* will do something on all the bugs in Bears, and the scripts with suffix *bug* will do something on a single bug given as input to the script.

I just updated the README of this repository with the usage of the scripts.

If this issue is solved, please close it, and if you have any other question (about something different), don't hesitate to open a new issue.

**Comment by ShangwenWang** [comment]
Yeah. Thanks a lot.
